server:
  port: 18001
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 86400s
      cookie:
        http-only: true
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  # 解决Swagger/Knife4j空指针核心配置
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  output:
    ansi:
      enabled: always
  session:
    store-type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

  freemarker:
    enabled: true
    suffix: .html
    # if you want to deploy html files separately(not in jar files), uncomment below
    # cache: false
    # template-loader-path: file:./templates/

mybatis-plus:
  configuration:
    cache-enabled: false
    local-cache-scope: statement
  mapper-locations:
    - classpath:dao/**/*.xml
    - classpath*:dr/sbs/mp/mapper/*.xml

logging:
  level:
    org.springframework.web: ERROR
    dr.sbs: DEBUG
  file:
    # 这里用path会多一级spring.log目录出来
    name: ./logs

app:
  # snowflake workerId and dataCenterId, see "hutool IdUtil.createSnowflake(workerId, dataCenterId)"
  workerId: 1
  dataCenterId: 1
